// prototype/src/components/CenterPeek.tsx
import React, { useState } from 'react';
import { 
  X, 
  ChevronUp, 
  ChevronDown, 
  Sparkles, 
  Star, 
  Clock, 
  Archive, 
  Trash2, 
  Mail, 
  Reply, 
  Forward, 
  Plus, 
  CornerUpLeft, 
  Send,
  MoreVertical,
  Bell
} from 'lucide-react';
import { Email } from '../types';
import { getLabelConfig, iconMapping, colorConfigs } from '../data/labelConfig';

const getInitials = (name: string) => {
  if (!name) return "?";
  const cleanName = name.replace(/[<>"']/g, '').trim();
  const parts = cleanName.split(/\s+/);
  if (parts.length > 1) {
    return (parts[0][0] + parts[1][0]).toUpperCase();
  }
  return cleanName.substring(0, 2).toUpperCase();
};

const getAvatarColor = (name: string) => {
  const colors = [
    'bg-red-500/10 text-red-400 border-red-500/20',
    'bg-orange-500/10 text-orange-400 border-orange-500/20',
    'bg-amber-500/10 text-amber-400 border-amber-500/20',
    'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    'bg-teal-500/10 text-teal-400 border-teal-500/20',
    'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
    'bg-sky-500/10 text-sky-400 border-sky-500/20',
    'bg-blue-500/10 text-blue-400 border-blue-500/20',
    'bg-indigo-500/10 text-indigo-400 border-indigo-500/20',
    'bg-violet-500/10 text-violet-400 border-violet-500/20',
    'bg-fuchsia-500/10 text-fuchsia-400 border-fuchsia-500/20',
    'bg-pink-500/10 text-pink-400 border-pink-500/20',
    'bg-rose-500/10 text-rose-400 border-rose-500/20',
  ];
  let hash = 0;
  for (let i = 0; i < name.length; i++) {
    hash = name.charCodeAt(i) + ((hash << 5) - hash);
  }
  const index = Math.abs(hash) % colors.length;
  return colors[index];
};

interface CenterPeekProps {
  email: Email | null;
  onClose: () => void;
  onNavigate: (direction: 'prev' | 'next') => void;
  hasPrev: boolean;
  hasNext: boolean;
  onArchive: (id: string) => void;
  onDelete: (id: string) => void;
  onToggleStar: (id: string) => void;
  onToggleUnread: (id: string) => void;
  onAddLabel: (id: string, label: string) => void;
  onRemoveLabel: (id: string, label: string) => void;
  onSendReply: (emailId: string, replyBody: string) => void;
  labelCustomizations?: Record<string, { iconName: string; colorName: string }>;
}

export default function CenterPeek({
  email,
  onClose,
  onNavigate,
  hasPrev,
  hasNext,
  onArchive,
  onDelete,
  onToggleStar,
  onToggleUnread,
  onAddLabel,
  onRemoveLabel,
  onSendReply,
  labelCustomizations
}: CenterPeekProps) {
  const [newLabelText, setNewLabelText] = useState('');
  const [showAddLabelInput, setShowAddLabelInput] = useState(false);
  const [replyText, setReplyText] = useState('');
  const [showReplyDraft, setShowReplyDraft] = useState(false);
  const [mobileMoreMenuOpen, setMobileMoreMenuOpen] = useState(false);

  // Dynamic label style resolver with customizations
  const getLabelStyle = (labelName: string) => {
    const base = getLabelConfig(labelName);
    const custom = labelCustomizations?.[labelName];
    if (custom) {
      const icon = iconMapping[custom.iconName] || base.icon;
      const colorStyle = colorConfigs[custom.colorName];
      if (colorStyle) {
        return {
          name: labelName,
          icon,
          color: custom.colorName,
          bgColor: colorStyle.bg,
          textColor: colorStyle.text,
          borderColor: colorStyle.border
        };
      }
    }
    return base;
  };

  if (!email) return null;

  // Handles adding custom labels
  const handleAddLabelSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (newLabelText.trim()) {
      onAddLabel(email.id, newLabelText.trim());
      setNewLabelText('');
      setShowAddLabelInput(false);
    }
  };

  // Handles sending the inline reply draft
  const handleSendReplySubmit = () => {
    if (replyText.trim()) {
      onSendReply(email.id, replyText.trim());
      setReplyText('');
      setShowReplyDraft(false);
    }
  };

  return (
    <div 
      id="center-peek-overlay" 
      className="fixed inset-0 z-50 flex items-center justify-center p-0 md:p-4 bg-black/15 backdrop-blur-[1px]"
      onClick={onClose}
    >
      {/* Modal Container */}
      <div 
        id="center-peek-modal" 
        className="w-full md:max-w-4xl h-screen md:h-[85vh] bg-canvas-card flex flex-col rounded-none md:rounded-lg shadow-2xl overflow-hidden font-sans"
        onClick={(e) => e.stopPropagation()}
      >
        
        {/* Header toolbar */}
        <div id="peek-header" className="hidden md:flex px-4 py-3 bg-[#1c1b1b] items-center justify-between select-none">
          
          {/* Left tools: Close and navigation chevrons */}
          <div className="flex items-center gap-1">
            <button
              id="btn-peek-close"
              onClick={onClose}
              title="Close peek (Esc)"
              className="p-1.5 rounded-lg hover:bg-canvas-hover text-text-secondary hover:text-text-primary cursor-pointer transition-colors"
            >
              <X className="w-4 h-4" />
            </button>
            <div className="w-2" />
            <button
              id="btn-peek-prev"
              disabled={!hasPrev}
              onClick={() => onNavigate('prev')}
              title="Previous Email"
              className="p-1.5 rounded-lg hover:bg-canvas-hover text-text-secondary hover:text-text-primary disabled:opacity-30 disabled:pointer-events-none cursor-pointer transition-colors"
            >
              <ChevronUp className="w-4 h-4" />
            </button>
            <button
              id="btn-peek-next"
              disabled={!hasNext}
              onClick={() => onNavigate('next')}
              title="Next Email"
              className="p-1.5 rounded-lg hover:bg-canvas-hover text-text-secondary hover:text-text-primary disabled:opacity-30 disabled:pointer-events-none cursor-pointer transition-colors"
            >
              <ChevronDown className="w-4 h-4" />
            </button>
          </div>

          {/* Right tools */}
          <div className="hidden md:flex items-center gap-1.5 text-text-secondary">
            
            <button
              id="btn-peek-star"
              onClick={() => onToggleStar(email.id)}
              title={email.isStarred ? "Remove Star" : "Star Email"}
              className={`p-1.5 rounded-lg hover:bg-canvas-hover cursor-pointer transition-colors ${
                email.isStarred ? 'text-white' : 'hover:text-text-primary'
              }`}
            >
              <Star className={`w-4 h-4 ${email.isStarred ? 'fill-white text-white' : ''}`} />
            </button>

            <button
              id="btn-peek-unread"
              onClick={() => {
                onToggleUnread(email.id);
                onClose();
              }}
              title="Mark as Unread"
              className="p-1.5 rounded-lg hover:bg-canvas-hover hover:text-text-primary cursor-pointer transition-colors"
            >
              <Mail className="w-4 h-4" />
            </button>

            <button
              id="btn-peek-archive"
              onClick={() => {
                onArchive(email.id);
                onClose();
              }}
              title="Archive Email (e)"
              className="p-1.5 rounded-lg hover:bg-canvas-hover hover:text-text-primary cursor-pointer transition-colors"
            >
              <Archive className="w-4 h-4" />
            </button>

            <button
              id="btn-peek-delete"
              onClick={() => {
                onDelete(email.id);
                onClose();
              }}
              title="Delete Email"
              className="p-1.5 rounded-lg hover:bg-canvas-hover hover:text-text-primary cursor-pointer transition-colors"
            >
              <Trash2 className="w-4 h-4" />
            </button>

            <button
              id="btn-peek-more"
              onClick={() => alert("Additional actions: Snooze, Bell, and Mute configurations.")}
              title="More Actions"
              className="p-1.5 rounded-lg hover:bg-canvas-hover hover:text-text-primary cursor-pointer transition-colors"
            >
              <MoreVertical className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Modal Scrollable Content Container */}
        <div id="peek-scrollable-body" className="flex-1 overflow-y-auto px-4 md:px-8 py-6 space-y-6">
          
          {/* Subject Title and Labels Bar */}
          <div className="space-y-1.5">
            <h1 className="text-xl md:text-2xl font-semibold tracking-tight text-text-primary">
              {email.subject}
            </h1>

            {/* Label Management Section */}
            <div id="peek-labels-bar" className="flex flex-wrap items-center gap-1.5">
              {email.labels.map(label => {
                const labelMeta = getLabelStyle(label);
                const LabelIcon = labelMeta.icon;
                return (
                  <div 
                    key={label}
                    id={`peek-tag-${label}`}
                    className={`flex items-center gap-1 px-2 py-0.5 ${labelMeta.bgColor} ${labelMeta.textColor} ${labelMeta.borderColor} border font-mono text-[10px] rounded-full shadow-sm`}
                  >
                    <LabelIcon className="w-3 h-3" />
                    <span>{label}</span>
                    <button
                      id={`btn-remove-tag-${label}`}
                      onClick={() => onRemoveLabel(email.id, label)}
                      className="hover:bg-black/25 p-0.5 rounded-full text-current cursor-pointer transition-colors"
                    >
                      <X className="w-2 h-2" />
                    </button>
                  </div>
                );
              })}

              {showAddLabelInput ? (
                <form onSubmit={handleAddLabelSubmit} className="flex items-center gap-1.5">
                  <input
                    id="tag-input-field"
                    type="text"
                    autoFocus
                    placeholder="Tag name..."
                    value={newLabelText}
                    onChange={(e) => setNewLabelText(e.target.value)}
                    className="bg-canvas-base outline-none rounded-md px-2 py-0.5 text-[10px] text-text-primary font-mono"
                  />
                  <button
                    type="submit"
                    className="px-2 py-0.5 bg-white text-canvas-base text-[10px] font-medium rounded hover:bg-white/90 cursor-pointer"
                  >
                    Add
                  </button>
                  <button
                    type="button"
                    onClick={() => setShowAddLabelInput(false)}
                    className="p-1 text-text-secondary hover:text-text-primary cursor-pointer"
                  >
                    <X className="w-3 h-3" />
                  </button>
                </form>
              ) : (
                <button
                  id="btn-add-tag-trigger"
                  onClick={() => setShowAddLabelInput(true)}
                  title="Add Label"
                  className="flex items-center justify-center p-1 text-text-secondary hover:text-text-primary rounded-full cursor-pointer bg-canvas-hover hover:bg-canvas-hover/80 transition-colors shadow-sm"
                >
                  <Plus className="w-3.5 h-3.5" />
                </button>
              )}
            </div>
          </div>

          {/* Sender & Recipient Details */}
          <div id="sender-details-card" className="flex items-center justify-between bg-canvas-base/60 rounded-lg p-4 mb-2 gap-4">
            <div className="flex items-center gap-3 min-w-0">
              {/* Sender Avatar */}
              {email.avatar && (
                <div className="w-10 h-10 rounded-full overflow-hidden flex items-center justify-center border border-white/10 shrink-0">
                  {email.avatar.startsWith('http') || email.avatar.startsWith('/') ? (
                    <img 
                      src={email.avatar} 
                      alt={email.sender} 
                      className="w-full h-full object-cover"
                      referrerPolicy="no-referrer"
                    />
                  ) : (
                    <div className={`w-full h-full flex items-center justify-center font-semibold text-sm ${getAvatarColor(email.sender)}`}>
                      {email.avatar}
                    </div>
                  )}
                </div>
              )}
              <div className="space-y-0.5 min-w-0">
                <div className="flex flex-wrap items-center gap-1.5 text-sm min-w-0">
                  <span className="font-medium text-text-primary truncate">{email.sender}</span>
                  <span className="text-text-secondary text-xs font-mono truncate">&lt;{email.senderEmail}&gt;</span>
                </div>
                <div className="text-xs text-text-secondary truncate">
                  <span>To: </span>
                  <span className="font-mono">{email.to}</span>
                </div>
              </div>
            </div>

            {/* Timestamps */}
            <div className="text-right shrink-0">
              <span className="text-xs font-mono text-text-secondary">
                {new Date(email.timestamp).toLocaleString([], { 
                  weekday: 'short', 
                  month: 'short', 
                  day: 'numeric', 
                  hour: '2-digit', 
                  minute: '2-digit' 
                })}
              </span>
            </div>
          </div>

          {/* Render Email HTML Body */}
          <div 
            id="email-body-rendered" 
            className="prose prose-invert max-w-none text-sm text-text-primary font-sans leading-relaxed selection:bg-white/20"
            dangerouslySetInnerHTML={{ __html: email.body }}
          />

          {/* Interactive Response Composer Block */}
          {showReplyDraft ? (
            <div id="reply-composer-container" className="bg-canvas-base/80 p-5 mt-8 space-y-4 rounded-lg">
              <div className="flex items-center gap-2 text-xs text-text-secondary font-mono pb-3">
                <CornerUpLeft className="w-3.5 h-3.5" />
                <span>Replying to <strong>{email.senderEmail}</strong></span>
              </div>
              
              <textarea
                id="reply-textarea-field"
                rows={4}
                autoFocus
                value={replyText}
                onChange={(e) => setReplyText(e.target.value)}
                placeholder="Type your response draft here..."
                className="w-full bg-transparent outline-none resize-none text-sm text-text-primary placeholder:text-text-secondary/50 font-sans"
              />

              <div className="flex items-center justify-between pt-4">
                <div className="text-[10px] font-mono text-text-secondary">
                  Press <kbd className="bg-canvas-hover px-1.5 py-0.5 rounded text-[10px]">Send</kbd> to dispatch.
                </div>
                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={() => setShowReplyDraft(false)}
                    className="px-3.5 py-2 rounded-md text-xs text-text-secondary hover:text-text-primary cursor-pointer bg-canvas-card hover:bg-canvas-hover"
                  >
                    Cancel
                  </button>
                  <button
                    type="button"
                    onClick={handleSendReplySubmit}
                    className="flex items-center gap-1.5 px-3 py-1.5 bg-white text-canvas-base font-medium rounded text-xs hover:bg-white/90 cursor-pointer"
                  >
                    <Send className="w-3.5 h-3.5" />
                    <span>Send reply</span>
                  </button>
                </div>
              </div>
            </div>
          ) : (
            <div className="pt-8 flex justify-center">
              <button
                id="reply-composer-trigger-btn"
                onClick={() => setShowReplyDraft(true)}
                className="flex items-center gap-2 px-4 py-2 bg-canvas-card hover:bg-canvas-hover rounded-md text-xs text-text-primary cursor-pointer transition-colors shadow-sm"
              >
                <Reply className="w-3.5 h-3.5" />
                <span>Write a response...</span>
              </button>
            </div>
          )}

        </div>

        {/* Mobile Bottom Action Bar */}
        <div 
          id="peek-mobile-bottom-actions" 
          className="md:hidden border-t border-white/10 bg-[#1c1b1b] px-4 py-3 flex items-center justify-around select-none"
        >
          <button
            id="mobile-action-close"
            onClick={onClose}
            className="p-2.5 rounded-full hover:bg-canvas-hover text-text-secondary hover:text-white transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
          
          {/* More menu trigger for Mobile */}
          <div className="relative">
            <button
              id="mobile-action-more"
              onClick={() => setMobileMoreMenuOpen(!mobileMoreMenuOpen)}
              className={`p-2.5 rounded-full hover:bg-canvas-hover transition-colors ${
                mobileMoreMenuOpen ? 'text-white bg-canvas-hover' : 'text-text-secondary'
              }`}
            >
              <MoreVertical className="w-5 h-5" />
            </button>
            
            {mobileMoreMenuOpen && (
              <div 
                className="absolute bottom-14 left-0 w-48 bg-[#1e1d1d] border border-white/15 rounded-lg py-1 shadow-2xl z-50 animate-fade-in"
                onClick={(e) => e.stopPropagation()}
              >
                <button
                  onClick={() => {
                    onToggleUnread(email.id);
                    onClose();
                    setMobileMoreMenuOpen(false);
                  }}
                  className="w-full text-left px-4 py-2.5 text-xs text-text-primary hover:bg-white/10 flex items-center gap-2"
                >
                  <Mail className="w-4 h-4" />
                  <span>Mark as Unread</span>
                </button>
                <button
                  onClick={() => {
                    setShowAddLabelInput(true);
                    setMobileMoreMenuOpen(false);
                    setTimeout(() => {
                      const el = document.getElementById('tag-input-field');
                      if (el) el.focus();
                    }, 100);
                  }}
                  className="w-full text-left px-4 py-2.5 text-xs text-text-primary hover:bg-white/10 flex items-center gap-2"
                >
                  <Plus className="w-4 h-4" />
                  <span>Add Label</span>
                </button>
                <button
                  onClick={() => {
                    alert(`Email details: Sender is ${email.senderEmail}, Category: ${email.category}`);
                    setMobileMoreMenuOpen(false);
                  }}
                  className="w-full text-left px-4 py-2.5 text-xs text-text-primary hover:bg-white/10 flex items-center gap-2"
                >
                  <Bell className="w-4 h-4" />
                  <span>Show details</span>
                </button>
              </div>
            )}
          </div>

          <button
            id="mobile-action-star"
            onClick={() => onToggleStar(email.id)}
            className={`p-2.5 rounded-full hover:bg-canvas-hover transition-colors ${
              email.isStarred ? 'text-yellow-400' : 'text-text-secondary hover:text-white'
            }`}
          >
            <Star className={`w-5 h-5 ${email.isStarred ? 'fill-current' : ''}`} />
          </button>

          <button
            id="mobile-action-archive"
            onClick={() => {
              onArchive(email.id);
              onClose();
            }}
            className="p-2.5 rounded-full hover:bg-canvas-hover text-text-secondary hover:text-white transition-colors"
          >
            <Archive className="w-5 h-5" />
          </button>

          <button
            id="mobile-action-reply"
            onClick={() => {
              setShowReplyDraft(true);
              setTimeout(() => {
                const el = document.getElementById('reply-editor-box');
                if (el) el.scrollIntoView({ behavior: 'smooth' });
              }, 100);
            }}
            className="p-2.5 rounded-full hover:bg-canvas-hover text-text-secondary hover:text-white transition-colors"
          >
            <Reply className="w-5 h-5" />
          </button>

          <button
            id="mobile-action-delete"
            onClick={() => {
              onDelete(email.id);
              onClose();
            }}
            className="p-2.5 rounded-full hover:bg-red-500/10 text-text-secondary hover:text-red-400 transition-colors"
          >
            <Trash2 className="w-5 h-5" />
          </button>
        </div>

      </div>
    </div>
  );
}

// frontend-mail/src/lib/components/CenterPeek.svelte
<script lang="ts">
  import { Avatar, Button } from '@kestrel/shared';
  import {
    X,
    ChevronUp,
    ChevronDown,
    Star,
    Archive,
    Trash2,
    Mail,
    Reply,
    ReplyAll,
    Forward,
    Plus,
    CornerUpLeft,
    Send,
    Sparkles,
    Check,
    Clock,
    FileText,
    MoreVertical,
    Tag,
    Paperclip
  } from 'lucide-svelte';
  import { 
    labelCustomizations, 
    getLabelStyle,
    EmailPillInput
  } from '@kestrel/shared';

  export interface Email {
    id: string;
    sender: string;
    senderEmail: string;
    to: string;
    subject: string;
    body: string;
    timestamp: string;
    isUnread: boolean;
    isStarred: boolean;
    isArchived: boolean;
    isTrash: boolean;
    labels: string[];
    avatar?: string;
  }

  let {
    email = null,
    onClose = () => {},
    onNavigate = (dir: 'prev' | 'next') => {},
    hasPrev = false,
    hasNext = false,
    onArchive = (id: string) => {},
    onDelete = (id: string) => {},
    onToggleStar = (id: string) => {},
    onToggleUnread = (id: string) => {},
    onAddLabel = (id: string, label: string) => {},
    onRemoveLabel = (id: string, label: string) => {},
    onSendReply = (emailId: string, replyBody: string) => {},
    historicalMessages = [] as { sender: string; body: string; timestamp: string }[]
  } = $props<{
    email?: Email | null;
    onClose?: () => void;
    onNavigate?: (direction: 'prev' | 'next') => void;
    hasPrev?: boolean;
    hasNext?: boolean;
    onArchive?: (id: string) => void;
    onDelete?: (id: string) => void;
    onToggleStar?: (id: string) => void;
    onToggleUnread?: (id: string) => void;
    onAddLabel?: (id: string, label: string) => void;
    onRemoveLabel?: (id: string, label: string) => void;
    onSendReply?: (emailId: string, replyBody: string) => void;
    historicalMessages?: { sender: string; body: string; timestamp: string }[];
  }>();

  // UI state variables
  let showReplyDraft = $state(false);
  let replyType = $state<'reply' | 'reply_all' | 'forward'>('reply');
  let replyToRecipients = $state<string[]>([]);
  let replyText = $state('');
  let newLabelText = $state('');
  let showAddLabelInput = $state(false);

  // AI Summary panel state
  let isAiSummaryLoading = $state(false);
  let aiSummaryText = $state<string | null>(null);
  let showAiSummary = $state(false);
  
  let showHistory = $state(false);

  function handleSendReply() {
    if (replyText.trim() && email) {
      onSendReply(email.id, replyText.trim());
      replyText = '';
      replyToRecipients = [];
      showReplyDraft = false;
    }
  }

  function handleAddLabelSubmit(e: SubmitEvent) {
    e.preventDefault();
    if (newLabelText.trim() && email) {
      onAddLabel(email.id, newLabelText.trim());
      newLabelText = '';
      showAddLabelInput = false;
    }
  }

  function handleTriggerAiSummary() {
    if (showAiSummary) {
      showAiSummary = false;
      return;
    }

    isAiSummaryLoading = true;
    showAiSummary = true;
    aiSummaryText = null;

    setTimeout(() => {
      isAiSummaryLoading = false;
      aiSummaryText = "Kestrel AI Summary:\n• Action required: Review and upgrade vulnerable node package dependencies immediately.\n• Primary focus: High vulnerability issue found in frontend/backend libraries.\n• Owner: Alex Rivera.";
    }, 1200);
  }
</script>

{#if email}
  <div
    id="center-peek-overlay"
    class="fixed inset-0 z-50 flex items-center justify-center p-0 md:p-4 bg-black/50 backdrop-blur-[2px]"
    role="button"
    tabindex="0"
    onclick={onClose}
    onkeydown={(e) => e.key === 'Escape' && onClose()}
  >
    <!-- Modal Container -->
    <div
      id="center-peek-modal"
      class="w-full md:max-w-4xl h-screen md:h-[90vh] bg-[#0d0d0d] flex flex-col rounded-none md:rounded-xl shadow-2xl overflow-hidden font-sans border border-[var(--color-border-hairline)]"
      role="dialog"
      aria-modal="true"
      tabindex="-1"
      onclick={(e) => e.stopPropagation()}
      onkeydown={(e) => e.stopPropagation()}
    >
      <!-- Header Toolbar -->
      <div 
        id="peek-header" 
        class="flex px-4 py-2 bg-[var(--color-canvas-base)] items-center justify-between select-none shrink-0"
        onpointerdown={(e) => {
          if (e.target === e.currentTarget) {
            import('@tauri-apps/api/window').then(m => m.getCurrentWindow().startDragging());
          }
        }}
      >
        <!-- Left tools -->
        <div class="flex items-center gap-1">
          <Button variant="ghost" size="sm" disabled={!hasPrev} onClick={() => onNavigate('prev')} title="Previous Email">
            <ChevronUp class="w-4 h-4" />
          </Button>
          <Button variant="ghost" size="sm" disabled={!hasNext} onClick={() => onNavigate('next')} title="Next Email">
            <ChevronDown class="w-4 h-4" />
          </Button>
        </div>

        <!-- AI Magic & Actions toolbar -->
        <div class="flex items-center gap-1.5">
          <button
            onclick={handleTriggerAiSummary}
            class="flex items-center gap-1 px-3 py-1.5 rounded-lg text-xs font-semibold bg-blue-500/10 hover:bg-blue-500/20 text-blue-400 border border-blue-500/10 transition-colors cursor-pointer mr-2"
          >
            <Sparkles class="w-3.5 h-3.5 text-blue-400" />
            <span>AI Summary</span>
          </button>
          
          <Button variant="ghost" size="sm" onClick={() => { onToggleUnread(email!.id); onClose(); }} title="Mark as Unread">
            <Mail class="w-4 h-4 text-[var(--color-text-secondary)]" />
          </Button>
          <Button variant="ghost" size="sm" onClick={() => { onArchive(email!.id); onClose(); }} title="Archive Email (e)">
            <Archive class="w-4 h-4 text-[var(--color-text-secondary)]" />
          </Button>
          <Button variant="danger" size="sm" onClick={() => { onDelete(email!.id); onClose(); }} title="Delete Email">
            <Trash2 class="w-4 h-4" />
          </Button>
          
          <div class="w-px h-5 bg-[var(--color-border-hairline)] mx-1"></div>

          <Button variant="ghost" size="sm" onClick={() => {}} title="Print">
            <FileText class="w-4 h-4 text-[var(--color-text-secondary)]" />
          </Button>
          <Button variant="ghost" size="sm" onClick={() => {}} title="More actions">
            <MoreVertical class="w-4 h-4 text-[var(--color-text-secondary)]" />
          </Button>
          <div class="w-px h-5 bg-[var(--color-border-hairline)] mx-1"></div>
          <Button variant="ghost" size="sm" onClick={onClose} title="Close peek (Esc)">
            <X class="w-4 h-4" />
          </Button>
        </div>
      </div>

      <!-- Scrollable Body -->
      <div id="peek-scrollable-body" class="flex-1 overflow-y-auto px-6 md:px-8 py-6 space-y-6 bg-[var(--color-canvas-base)]">
        
        <!-- Subject & Labels Bar -->
        <div class="space-y-2">
          <h1 class="text-xl md:text-2xl font-bold tracking-tight text-[var(--color-text-primary)]">
            {email.subject}
          </h1>

          <!-- Correctly visible and editable labels bar using customizations -->
          <div id="peek-labels-bar" class="flex flex-wrap items-center gap-1.5">
            {#each email.labels as label}
              {@const labelStyle = getLabelStyle(label, $labelCustomizations)}
              <span class="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[10px] font-medium border {labelStyle.bgColor} {labelStyle.textColor} {labelStyle.borderColor} animate-fadeIn">
                <span>{label.split('/').pop()}</span>
                <button
                  onclick={() => onRemoveLabel(email!.id, label)}
                  class="hover:bg-white/10 p-0.5 rounded-full text-current cursor-pointer transition-colors"
                  title="Remove label"
                >
                  <X class="w-2.5 h-2.5" />
                </button>
              </span>
            {/each}

            {#if showAddLabelInput}
              <form onsubmit={handleAddLabelSubmit} class="flex items-center gap-1.5">
                <input
                  type="text"
                  placeholder="Tag name..."
                  bind:value={newLabelText}
                  class="bg-[var(--color-canvas-card)] border border-[var(--color-border-hairline)] rounded px-2.5 py-1 text-[11px] text-white outline-none font-mono focus:border-white/20 transition-all"
                />
                <Button variant="primary" size="sm">Add</Button>
                <Button variant="ghost" size="sm" onClick={() => showAddLabelInput = false}><X class="w-3 h-3" /></Button>
              </form>
            {:else}
              <Button variant="ghost" size="sm" onClick={() => showAddLabelInput = true} title="Add Label">
                <Plus class="w-3.5 h-3.5" />
              </Button>
            {/if}
          </div>
        </div>

        <!-- AI Summary expanded card -->
        {#if showAiSummary}
          <div class="p-4 bg-blue-500/5 border border-blue-500/10 rounded-xl space-y-2 animate-slideDown">
            <div class="flex items-center justify-between">
              <div class="flex items-center gap-2 text-xs font-semibold text-blue-400">
                <Sparkles class="w-3.5 h-3.5" />
                <span>Kestrel AI Assistant</span>
              </div>
              <button onclick={() => showAiSummary = false} class="text-[var(--color-text-secondary)] hover:text-white transition-colors">
                <X class="w-3.5 h-3.5" />
              </button>
            </div>
            
            {#if isAiSummaryLoading}
              <div class="flex items-center gap-2 py-2 text-xs text-[var(--color-text-secondary)]">
                <span class="w-1.5 h-1.5 rounded-full bg-blue-400 animate-ping"></span>
                <span>Generating digest summary...</span>
              </div>
            {:else}
              <pre class="text-xs text-[var(--color-text-primary)] font-sans whitespace-pre-wrap leading-relaxed">
                {aiSummaryText}
              </pre>
            {/if}
          </div>
        {/if}

        <!-- Message Thread Stack using shared Reusable Avatar component -->
        {#if historicalMessages && historicalMessages.length > 0}
          <div class="space-y-3.5 border-b border-[var(--color-border-hairline)]/30 pb-4">
            {#if !showHistory}
              <button 
                onclick={() => showHistory = true}
                class="flex items-center gap-2 px-3 py-1.5 rounded-full bg-[var(--color-canvas-card)] border border-[var(--color-border-hairline)] text-xs text-[var(--color-text-secondary)] hover:text-white transition-colors mx-auto cursor-pointer"
              >
                <MoreVertical class="w-3.5 h-3.5" />
                <span>Show {historicalMessages.length} earlier messages</span>
              </button>
            {:else}
              <div class="flex items-center justify-between">
                <span class="text-[10px] font-mono tracking-widest text-[var(--color-text-secondary)]/50 uppercase">Conversation Thread</span>
                <button onclick={() => showHistory = false} class="text-xs text-blue-400 hover:underline cursor-pointer">Hide</button>
              </div>
              {#each historicalMessages as msg}
                <div class="flex gap-3 items-start border border-[var(--color-border-hairline)]/20 rounded-xl p-3.5 bg-[#131313]/20">
                  <Avatar name={msg.sender} size={28} />
                  <div class="space-y-1 min-w-0 flex-1">
                    <div class="flex items-baseline justify-between">
                      <span class="text-xs font-semibold text-white">{msg.sender}</span>
                      <span class="text-[9px] font-mono text-[var(--color-text-secondary)]">{msg.timestamp}</span>
                    </div>
                    <p class="text-xs text-[var(--color-text-primary)] leading-relaxed">{@html msg.body}</p>
                  </div>
                </div>
              {/each}
            {/if}
          </div>
        {/if}

        <!-- Primary Message Body -->
        <div class="space-y-4">
          <!-- Sender Card -->
          <div class="flex items-center justify-between bg-[#131313] border border-[var(--color-border-hairline)] rounded-xl p-4 gap-4">
            <div class="flex items-center gap-3 min-w-0">
              <Avatar name={email.sender} size="md" />
              <div class="space-y-0.5 min-w-0">
                <div class="flex items-center gap-1.5 text-sm min-w-0">
                  <span class="font-semibold text-white truncate">{email.sender}</span>
                  <span class="text-[var(--color-text-secondary)] text-xs font-mono truncate">&lt;{email.senderEmail}&gt;</span>
                </div>
                <div class="text-xs text-[var(--color-text-secondary)] truncate">
                  To: <span class="font-mono">{email.to}</span>
                </div>
              </div>
            </div>

            <div class="flex items-center gap-3 shrink-0">
              <span class="text-xs font-mono text-[var(--color-text-secondary)] hidden sm:block">
                {email.timestamp}
              </span>
              <button 
                onclick={(e) => { e.stopPropagation(); onToggleStar(email!.id); }}
                class="p-1.5 rounded-full hover:bg-white/5 transition-colors cursor-pointer"
                title={email.isStarred ? "Remove Star" : "Star Email"}
              >
                <Star class="w-4 h-4 {email.isStarred ? 'fill-current text-amber-400' : 'text-[var(--color-text-secondary)]'}" />
              </button>
              <button class="p-1.5 rounded-full hover:bg-white/5 text-[var(--color-text-secondary)] transition-colors cursor-pointer">
                <Reply class="w-4 h-4" />
              </button>
            </div>
          </div>

          <!-- Message HTML Render Content -->
          <div class="prose prose-invert max-w-none text-sm text-[var(--color-text-primary)] font-sans leading-[1.7] border border-[var(--color-border-hairline)]/30 rounded-xl p-5 bg-[#131313]/10">
            {@html email.body}
          </div>

          <!-- Attachment Mock -->
          <div class="flex gap-3 overflow-x-auto pb-2">
            <div class="flex items-center gap-3 px-3 py-2 bg-[var(--color-canvas-card)] border border-[var(--color-border-hairline)] rounded-lg shrink-0 cursor-pointer hover:bg-[var(--color-canvas-hover)] transition-colors">
              <div class="w-8 h-8 rounded bg-blue-500/10 flex items-center justify-center text-blue-400">
                <FileText class="w-4 h-4" />
              </div>
              <div class="flex flex-col">
                <span class="text-xs font-semibold text-white">Project_Brief_v2.pdf</span>
                <span class="text-[10px] text-[var(--color-text-secondary)]">2.4 MB</span>
              </div>
            </div>
            <div class="flex items-center gap-3 px-3 py-2 bg-[var(--color-canvas-card)] border border-[var(--color-border-hairline)] rounded-lg shrink-0 cursor-pointer hover:bg-[var(--color-canvas-hover)] transition-colors">
              <div class="w-8 h-8 rounded bg-purple-500/10 flex items-center justify-center text-purple-400">
                <Paperclip class="w-4 h-4" />
              </div>
              <div class="flex flex-col">
                <span class="text-xs font-semibold text-white">budget_q3.xlsx</span>
                <span class="text-[10px] text-[var(--color-text-secondary)]">1.1 MB</span>
              </div>
            </div>
          </div>
        </div>



        <!-- Action Buttons / Inline Reply Editor -->
        {#if !showReplyDraft}
          <div class="flex items-center gap-3 pt-2">
            <button
              onclick={() => { 
                replyType = 'reply'; 
                replyToRecipients = email.senderEmail ? [email.senderEmail] : [email.sender]; 
                showReplyDraft = true; 
              }}
              class="flex items-center gap-2 px-4 py-2.5 bg-[var(--color-canvas-card)] hover:bg-[var(--color-canvas-hover)] text-white text-xs font-medium rounded-xl border border-[var(--color-border-hairline)] transition-all cursor-pointer shadow-sm hover:border-white/20 active:scale-95"
            >
              <Reply class="w-4 h-4 text-blue-400" />
              <span>Reply</span>
            </button>

            <button
              onclick={() => { 
                replyType = 'reply_all'; 
                replyToRecipients = [email.senderEmail || email.sender, 'alex@kestrel.dev']; 
                showReplyDraft = true; 
              }}
              class="flex items-center gap-2 px-4 py-2.5 bg-[var(--color-canvas-card)] hover:bg-[var(--color-canvas-hover)] text-white text-xs font-medium rounded-xl border border-[var(--color-border-hairline)] transition-all cursor-pointer shadow-sm hover:border-white/20 active:scale-95"
            >
              <ReplyAll class="w-4 h-4 text-indigo-400" />
              <span>Reply All</span>
            </button>

            <button
              onclick={() => { 
                replyType = 'forward'; 
                replyToRecipients = []; 
                showReplyDraft = true; 
              }}
              class="flex items-center gap-2 px-4 py-2.5 bg-[var(--color-canvas-card)] hover:bg-[var(--color-canvas-hover)] text-white text-xs font-medium rounded-xl border border-[var(--color-border-hairline)] transition-all cursor-pointer shadow-sm hover:border-white/20 active:scale-95"
            >
              <Forward class="w-4 h-4 text-purple-400" />
              <span>Forward</span>
            </button>
          </div>
        {:else}
          <!-- Expanded rich editor -->
          <div class="border border-[var(--color-border-hairline)] rounded-xl overflow-hidden bg-[#131313] p-4 space-y-3 animate-fadeIn">
            <div class="flex items-center justify-between border-b border-[var(--color-border-hairline)]/60 pb-2">
              <div class="flex items-center gap-2 text-xs font-semibold text-white">
                {#if replyType === 'reply'}
                  <Reply class="w-3.5 h-3.5 text-blue-400" />
                  <span>Replying</span>
                {:else if replyType === 'reply_all'}
                  <ReplyAll class="w-3.5 h-3.5 text-indigo-400" />
                  <span>Replying All</span>
                {:else}
                  <Forward class="w-3.5 h-3.5 text-purple-400" />
                  <span>Forwarding Message</span>
                {/if}
              </div>
              <button 
                onclick={() => showReplyDraft = false}
                class="text-[var(--color-text-secondary)] hover:text-white transition-colors cursor-pointer"
              >
                <X class="w-4 h-4" />
              </button>
            </div>

            <!-- Editable Recipients Input Field with Email Pills -->
            <div class="flex items-center gap-2 px-3 py-1 bg-[var(--color-canvas-base)] rounded-lg border border-[var(--color-border-hairline)] text-xs focus-within:border-white/30 transition-colors">
              <span class="text-[var(--color-text-secondary)] font-mono text-[11px] w-6 shrink-0">To:</span>
              <EmailPillInput bind:recipients={replyToRecipients} placeholder="recipient@example.com" />
            </div>

            <textarea
              bind:value={replyText}
              placeholder={replyType === 'forward' ? "Add forwarding note..." : "Write your response..."}
              rows="5"
              class="w-full bg-[var(--color-canvas-base)] rounded-lg text-xs text-white outline-none border border-[var(--color-border-hairline)] resize-none font-sans p-3 focus:border-blue-500/50 transition-colors"
            ></textarea>

            <div class="flex justify-between items-center pt-2">
              <div class="flex items-center gap-1.5">
                <button onclick={() => replyText += '**text**'} class="p-1.5 rounded hover:bg-white/5 text-[var(--color-text-secondary)] transition-colors cursor-pointer" title="Bold"><strong class="font-serif font-bold">B</strong></button>
                <button onclick={() => replyText += '*text*'} class="p-1.5 rounded hover:bg-white/5 text-[var(--color-text-secondary)] transition-colors cursor-pointer" title="Italic"><em class="font-serif">I</em></button>
                <button onclick={() => replyText += '<u>text</u>'} class="p-1.5 rounded hover:bg-white/5 text-[var(--color-text-secondary)] transition-colors cursor-pointer" title="Underline"><span class="underline">U</span></button>
              </div>
              <div class="flex items-center gap-2">
                <Button variant="ghost" size="sm" onClick={() => showReplyDraft = false}>Discard</Button>
                <button
                  onclick={handleSendReply}
                  class="flex items-center gap-1.5 px-3.5 py-1.5 text-xs font-semibold bg-white text-black hover:bg-neutral-200 rounded-lg transition-all active:scale-95 cursor-pointer"
                >
                  <Send class="w-3.5 h-3.5" />
                  <span>{replyType === 'forward' ? 'Forward Email' : 'Send Reply'}</span>
                </button>
              </div>
            </div>
          </div>
        {/if}

      </div>
    </div>
  </div>
{/if}
