// prototype/src/components/ComposeModal.tsx
import React, { useState } from 'react';
import { X, Send, Paperclip } from 'lucide-react';
import { Email } from '../types';

interface ComposeModalProps {
  onClose: () => void;
  onSend: (newEmail: Omit<Email, 'id' | 'timestamp'>) => void;
}

export default function ComposeModal({ onClose, onSend }: ComposeModalProps) {
  const [to, setTo] = useState('');
  const [subject, setSubject] = useState('');
  const [body, setBody] = useState(() => {
    try {
      const sig = localStorage.getItem('kestrel_mail_signature') || 'Sent from Kestrel Mail';
      return `\n\n--\n${sig}`;
    } catch {
      return '\n\n--\nSent from Kestrel Mail';
    }
  });
  const [hasAttachment, setHasAttachment] = useState(false);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!to.trim() || !subject.trim() || !body.trim()) {
      alert("Please fill in all the fields before sending.");
      return;
    }

    onSend({
      sender: 'Developer',
      senderEmail: 'user@workspace.io',
      to: to.trim(),
      subject: subject.trim(),
      body: `<p style="font-family: sans-serif; line-height: 1.6; color: #e5e2e1;">${body.replace(/\n/g, '<br/>')}</p>`,
      isUnread: false,
      isArchived: false,
      isStarred: false,
      isDraft: false,
      isSpam: false,
      isTrash: false,
      hasAttachment,
      category: 'Primary',
      labels: ['Sent']
    });

    onClose();
  };

  return (
    <div 
      id="compose-modal-overlay" 
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-xs select-none"
    >
      <div 
        id="compose-modal-card" 
        className="w-full max-w-xl bg-canvas-card rounded-lg shadow-2xl flex flex-col font-sans"
      >
        {/* Header bar */}
        <div id="compose-header" className="px-4 py-3 bg-[#1c1b1b] flex items-center justify-between mb-1">
          <span className="text-xs font-mono font-medium text-text-primary uppercase tracking-wider">New Message</span>
          <button
            id="btn-close-compose"
            onClick={onClose}
            className="p-1 rounded hover:bg-canvas-hover text-text-secondary hover:text-text-primary cursor-pointer transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Form elements */}
        <form onSubmit={handleSubmit} className="p-4 flex flex-col gap-4">
          
          {/* Recipient line */}
          <div className="flex items-center gap-3 pb-3 mb-1">
            <span className="text-xs font-mono text-text-secondary w-12 text-right">To:</span>
            <input
              id="compose-to-input"
              type="email"
              required
              placeholder="recipient@example.com"
              value={to}
              onChange={(e) => setTo(e.target.value)}
              className="flex-1 bg-transparent border-none outline-none text-sm text-text-primary placeholder:text-text-secondary/40 font-sans"
            />
          </div>

          {/* Subject line */}
          <div className="flex items-center gap-3 pb-3 mb-1">
            <span className="text-xs font-mono text-text-secondary w-12 text-right">Subject:</span>
            <input
              id="compose-subject-input"
              type="text"
              required
              placeholder="What's this mail about?"
              value={subject}
              onChange={(e) => setSubject(e.target.value)}
              className="flex-1 bg-transparent border-none outline-none text-sm text-text-primary placeholder:text-text-secondary/40 font-sans font-medium"
            />
          </div>

          {/* Mail body input block */}
          <div className="flex flex-col gap-1">
            <textarea
              id="compose-body-input"
              required
              placeholder="Draft your mail content here..."
              value={body}
              onChange={(e) => setBody(e.target.value)}
              className="w-full h-40 sm:h-60 md:h-80 bg-transparent border-none outline-none resize-none text-sm text-text-primary placeholder:text-text-secondary/35 font-sans leading-relaxed"
            />
          </div>

          {/* Actions panel */}
          <div className="flex items-center justify-between pt-5 mt-4 select-none">
            
            {/* Attachment simulation trigger */}
            <button
              id="compose-attachment-btn"
              type="button"
              onClick={() => setHasAttachment(!hasAttachment)}
              className={`flex items-center gap-1.5 px-3 py-1.5 text-xs font-mono rounded transition-colors ${
                hasAttachment 
                  ? 'bg-canvas-hover text-white font-medium shadow-sm' 
                  : 'bg-canvas-card text-text-secondary hover:text-text-primary'
              }`}
            >
              <Paperclip className="w-3.5 h-3.5" />
              <span>{hasAttachment ? 'StatementAttached.pdf' : 'Add Attachment'}</span>
            </button>

            {/* Action buttons */}
            <div className="flex items-center gap-2">
              <button
                id="compose-btn-cancel"
                type="button"
                onClick={onClose}
                className="px-3.5 py-2 rounded-md text-xs text-text-secondary hover:text-text-primary hover:bg-canvas-hover cursor-pointer bg-canvas-card"
              >
                Cancel
              </button>
              <button
                id="compose-btn-send"
                type="submit"
                className="flex items-center gap-1.5 px-4 py-1.5 bg-white text-canvas-base font-semibold rounded-md text-xs hover:bg-white/90 cursor-pointer"
              >
                <Send className="w-3.5 h-3.5" />
                <span>Send message</span>
              </button>
            </div>

          </div>

        </form>
      </div>
    </div>
  );
}

// frontend-mail/src/lib/components/ComposeModal.svelte
<script lang="ts">
  import { X, Send, Paperclip, Bold, Italic, List, Link } from 'lucide-svelte';
  import { fade, fly } from 'svelte/transition';
  import { cubicOut } from 'svelte/easing';
  import { ContactAutocomplete } from '@kestrel/shared';
  import { apiClient } from '@kestrel/shared/api';
  import { onMount } from 'svelte';
  import { get } from 'svelte/store';
  import { mailSignature } from '@kestrel/shared/stores';

  let {
    isOpen = false,
    onClose = () => {},
    onSend = (draft: { to: string; cc?: string; bcc?: string; subject: string; body: string }) => {}
  } = $props<{
    isOpen?: boolean;
    onClose?: () => void;
    onSend?: (draft: { to: string; cc?: string; bcc?: string; subject: string; body: string }) => void;
  }>();

  let toRecipients = $state<string[]>([]);
  let ccRecipients = $state<string[]>([]);
  let bccRecipients = $state<string[]>([]);
  let showCc = $state(false);
  let showBcc = $state(false);
  let subject = $state('');
  let body = $state('');
  let attachments = $state<{ filename: string; content_type: string; base64_content: string; size: number }[]>([]);
  let fromAccount = $state('');
  let accounts = $state<any[]>([]);
  let isSending = $state(false);

  $effect(() => {
    if (isOpen) {
      loadAccounts();
      const sig = get(mailSignature);
      if (sig && body === '') {
        body = `<br><br>--<br>${sig}`;
      }
    } else {
      // Reset form when closed
      toRecipients = [];
      ccRecipients = [];
      bccRecipients = [];
      subject = '';
      body = '';
      attachments = [];
    }
  });

  async function loadAccounts() {
    try {
      accounts = await apiClient.get('/api/v1/accounts');
      if (accounts.length > 0 && !fromAccount) {
        fromAccount = accounts[0].id;
      }
    } catch (e) {
      console.error("Failed to load accounts for compose modal", e);
    }
  }

  async function handleSend() {
    if (!fromAccount) {
      alert("Please select a sending account");
      return;
    }
    
    isSending = true;
    try {
      await apiClient.post('/api/v1/messages/send', {
        account_id: fromAccount,
        to: toRecipients,
        cc: ccRecipients.length > 0 ? ccRecipients : undefined,
        bcc: bccRecipients.length > 0 ? bccRecipients : undefined,
        subject,
        body_html: body.replace(/\n/g, '<br/>'),
        attachments: attachments.length > 0 ? attachments.map(a => ({
          filename: a.filename,
          content_type: a.content_type,
          base64_content: a.base64_content
        })) : undefined
      });
      
      onSend({
        to: toRecipients.join(', '),
        cc: ccRecipients.length > 0 ? ccRecipients.join(', ') : undefined,
        bcc: bccRecipients.length > 0 ? bccRecipients.join(', ') : undefined,
        subject,
        body
      });
      
      toRecipients = [];
      ccRecipients = [];
      bccRecipients = [];
      showCc = false;
      showBcc = false;
      subject = '';
      body = '';
      attachments = [];
      onClose();
    } catch (e: any) {
      alert(`Failed to send message: ${e.message}`);
    } finally {
      isSending = false;
    }
  }

  function applyFormat(prefix: string, suffix: string = '') {
    body = body ? `${body}\n${prefix}text${suffix}` : `${prefix}text${suffix}`;
  }

  let fileInput: HTMLInputElement;

  function handleAttach(e: Event) {
    const target = e.target as HTMLInputElement;
    if (target.files && target.files.length > 0) {
      for (let i = 0; i < target.files.length; i++) {
        const file = target.files[i];
        const reader = new FileReader();
        reader.onload = (event) => {
          if (event.target?.result) {
            attachments = [...attachments, {
              filename: file.name,
              content_type: file.type || 'application/octet-stream',
              base64_content: event.target.result as string,
              size: file.size
            }];
          }
        };
        reader.readAsDataURL(file);
      }
    }
    target.value = ''; // Reset input
  }
</script>

{#if isOpen}
  <input type="file" bind:this={fileInput} onchange={handleAttach} class="hidden" multiple />
  <div transition:fade={{ duration: 200 }} class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-xs">
    <div transition:fly={{ y: 50, duration: 400, easing: cubicOut }} class="w-full max-w-2xl bg-[var(--color-canvas-card)] border border-[var(--color-border-hairline)] rounded-xl shadow-2xl flex flex-col overflow-hidden font-sans">
      <!-- Header -->
      <div class="px-4 py-3 border-b border-[var(--color-border-hairline)] flex items-center justify-between bg-[var(--color-canvas-card)]">
        <span class="text-xs font-medium text-[var(--color-text-secondary)] tracking-wide">New Message</span>
        <button onclick={onClose} class="p-1 rounded hover:bg-white/10 text-[var(--color-text-secondary)] hover:text-white transition-colors cursor-pointer">
          <X class="w-4 h-4" />
        </button>
      </div>

      <!-- Form Inputs (Borderless, Dividers) -->
      <div class="text-xs">
        <!-- From Account Row -->
        <div class="flex items-center px-4 py-2 border-b border-[var(--color-border-hairline)]/30">
          <span class="w-10 text-[var(--color-text-secondary)] font-mono shrink-0 select-none">From:</span>
          <select bind:value={fromAccount} class="flex-1 bg-transparent text-[var(--color-text-primary)] outline-none border-none cursor-pointer py-0.5">
            {#if accounts.length === 0}
              <option value="" class="bg-[var(--color-canvas-card)]">Loading accounts...</option>
            {/if}
            {#each accounts as account}
              <option value={account.id} class="bg-[var(--color-canvas-card)]">{account.email_address} ({account.provider})</option>
            {/each}
          </select>
        </div>

        <!-- To Row -->
        <div class="flex items-center px-4 py-1.5 border-b border-[var(--color-border-hairline)]/30">
          <span class="w-10 text-[var(--color-text-secondary)] font-mono shrink-0 select-none">To:</span>
          <div class="flex-1 flex items-center">
            <div class="flex-1">
              <ContactAutocomplete bind:recipients={toRecipients} placeholder="Recipients..." />
            </div>
            <div class="flex items-center gap-2 ml-2 text-[11px] text-[var(--color-text-secondary)] shrink-0 select-none">
              {#if !showCc}
                <button type="button" onclick={() => showCc = true} class="hover:text-white transition-colors cursor-pointer font-mono">Cc</button>
              {/if}
              {#if !showBcc}
                <button type="button" onclick={() => showBcc = true} class="hover:text-white transition-colors cursor-pointer font-mono">Bcc</button>
              {/if}
            </div>
          </div>
        </div>

        <!-- Cc Row -->
        {#if showCc}
          <div class="flex items-center px-4 py-1.5 border-b border-[var(--color-border-hairline)]/30">
            <div class="w-10 text-[var(--color-text-secondary)] font-mono shrink-0 flex items-center justify-between select-none">
              <span>Cc:</span>
              <button type="button" onclick={() => { showCc = false; ccRecipients = []; }} class="text-[10px] text-[var(--color-text-secondary)] hover:text-white mr-1.5 cursor-pointer">✕</button>
            </div>
            <div class="flex-1">
              <ContactAutocomplete bind:recipients={ccRecipients} placeholder="Cc recipients..." />
            </div>
          </div>
        {/if}

        <!-- Bcc Row -->
        {#if showBcc}
          <div class="flex items-center px-4 py-1.5 border-b border-[var(--color-border-hairline)]/30">
            <div class="w-10 text-[var(--color-text-secondary)] font-mono shrink-0 flex items-center justify-between select-none">
              <span>Bcc:</span>
              <button type="button" onclick={() => { showBcc = false; bccRecipients = []; }} class="text-[10px] text-[var(--color-text-secondary)] hover:text-white mr-1.5 cursor-pointer">✕</button>
            </div>
            <div class="flex-1">
              <ContactAutocomplete bind:recipients={bccRecipients} placeholder="Bcc recipients..." />
            </div>
          </div>
        {/if}

        <!-- Subject Field (Borderless, No label) -->
        <div class="px-4 py-2 border-b border-[var(--color-border-hairline)]/30">
          <input
            type="text"
            bind:value={subject}
            placeholder="Subject"
            class="w-full bg-transparent text-sm font-medium text-[var(--color-text-primary)] placeholder-[var(--color-text-secondary)]/60 outline-none border-none"
          />
        </div>
        
        <!-- Attachments Row -->
        {#if attachments.length > 0}
          <div class="px-4 py-2 border-b border-[var(--color-border-hairline)]/30 flex gap-2 flex-wrap bg-[var(--color-canvas-base)]/30">
            {#each attachments as att, index}
              <div class="flex items-center gap-1.5 bg-[var(--color-border-hairline)]/40 rounded px-2.5 py-1 text-[11px] text-[var(--color-text-primary)] font-medium">
                <Paperclip class="w-3.5 h-3.5 text-[var(--color-text-secondary)]" />
                <span>{att.filename}</span>
                <span class="text-[var(--color-text-secondary)]/60 font-mono text-[9px]">{(att.size / 1024).toFixed(0)}KB</span>
                <button type="button" onclick={() => attachments = attachments.filter((_, i) => i !== index)} class="ml-1 hover:text-white text-[var(--color-text-secondary)]"><X class="w-3 h-3" /></button>
              </div>
            {/each}
          </div>
        {/if}
      </div>

      <!-- Message Textarea Body -->
      <div class="p-4 flex-1">
        <textarea
          bind:value={body}
          placeholder="Write your email response or message here..."
          rows="10"
          class="w-full h-full bg-transparent text-[var(--color-text-primary)] text-xs outline-none resize-none leading-relaxed border-none"
        ></textarea>
      </div>

      <!-- Footer Actions & Style Controls -->
      <div class="px-4 py-3 border-t border-[var(--color-border-hairline)] flex items-center justify-between bg-[var(--color-canvas-card)]">
        <div class="flex items-center gap-2">
          <button disabled={isSending} onclick={handleSend} class="px-4 py-1.5 rounded bg-white text-black text-xs font-semibold hover:bg-neutral-200 transition-all flex items-center gap-1.5 cursor-pointer shadow-sm active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed">
            <Send class="w-3.5 h-3.5" />
            <span>{isSending ? 'Sending...' : 'Send Message'}</span>
          </button>

          <!-- Formatting Style Controls -->
          <div class="flex items-center gap-0.5 ml-2 border-l border-[var(--color-border-hairline)]/40 pl-2 text-[var(--color-text-secondary)]">
            <button onclick={() => applyFormat('**', '**')} title="Bold" class="p-1.5 rounded hover:bg-white/10 hover:text-white transition-colors cursor-pointer"><Bold class="w-3.5 h-3.5" /></button>
            <button onclick={() => applyFormat('*', '*')} title="Italic" class="p-1.5 rounded hover:bg-white/10 hover:text-white transition-colors cursor-pointer"><Italic class="w-3.5 h-3.5" /></button>
            <button onclick={() => applyFormat('- ')} title="List" class="p-1.5 rounded hover:bg-white/10 hover:text-white transition-colors cursor-pointer"><List class="w-3.5 h-3.5" /></button>
            <button onclick={() => applyFormat('[', '](https://)')} title="Link" class="p-1.5 rounded hover:bg-white/10 hover:text-white transition-colors cursor-pointer"><Link class="w-3.5 h-3.5" /></button>
            <button onclick={() => fileInput.click()} title="Attach File" class="p-1.5 rounded hover:bg-white/10 hover:text-white transition-colors cursor-pointer"><Paperclip class="w-3.5 h-3.5" /></button>
          </div>
        </div>

        <button onclick={onClose} class="px-3 py-1.5 rounded text-xs text-[var(--color-text-secondary)] hover:text-white cursor-pointer transition-colors" title="Discard draft">
          Discard Draft
        </button>
      </div>
    </div>
  </div>
{/if}
